### ISSUE TITLE
Ability to bind to a network adapter/IP

### ISSUE THREAD

**Issue by uujfwmnp** [BlankSourceCode/WebRTC-Telestrator#2]
I've got a possible user edge-case, is there an ability to bind the webrtc-telestrator app to a specific IP or network adapter? I'm in a spot where I want to use this on a computer that needs to connect to two different networks, and this means I'm having to use two network adapters.

Outside of this edge case, **huge** thank you for this utility. I've used it for my streams to draw strategies and goof around, it's great!

**Comment by BlankSourceCode** [comment]
@uujfwmnp Currently there isn't a way to change the address it binds to.

I've updated the script in [this branch](https://github.com/BlankSourceCode/WebRTC-Telestrator/tree/host-bind-params) to add a new `--httpHost` parameter to the exe, but I don't know if it works since I only have one address to bind to.

Could you give this attached file a try to see and let me know if it solves your issue:

[webrtc-telestrator-win.zip](https://github.com/BlankSourceCode/WebRTC-Telestrator/files/14201825/webrtc-telestrator-win.zip)

**Comment by BlankSourceCode** [comment]
You will probably still need to open the local browser to `http://localhost:<port>` to share the screen, since the browser blocks sharing from non-local http.

If a specific host ip address doesn't work for you, try using `--httpHost 0.0.0.0` to just bind to everything.

**Comment by uujfwmnp** [comment]
I can verify the `--hh` parameter works, since my first attempt I typed the wrong IP and it threw a nodeJS error!

So the binding works, but I can't get the site to load, it just sits until the connection times out.

**Comment by BlankSourceCode** [comment]
@uujfwmnp Which side times out? When you try to go to the webpage via a browser on your local machine to host a share session? Or when you visit the webpage from another machine to join? Or maybe it's the obs browser source that is timing out?

What ip address are you sending in, and what url are you going to? The advice in the prompt is probably wrong.

**Comment by uujfwmnp** [comment]
Ah sorry! OK I did a bit more troubleshooting. When `--httpHost` is defined, connecting via localhost does not work, so the host must specify the IP address in the browser and the OBS source.

Adapter 1 local IP: 192.168.x
Adapter 2 local IP: 172.20.x

So when I run `--httpHost 192.168.x.x` it responds on `192.168.x.x:8888` for host/OBS/client. It does not respond on `172.20.x.x`.

The bind *does* work, I was just testing it out backwards.

**Comment by BlankSourceCode** [comment]
@uujfwmnp Does that mean it works for your scenario, or is something still broken?

If it works, I'll merge the changes and publish a new version.

**Comment by uujfwmnp** [comment]
I should have dug deeper before posting, sorry. Came up on this crash when I started a host session:
```
C:\snapshot\webrtc-telestrator\src\server.js:85
                wsMessages.push(msg);
                ^

ReferenceError: wsMessages is not defined
    at WebSocket.<anonymous> (C:\snapshot\webrtc-telestrator\src\server.js:85:17)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (C:\snapshot\webrtc-telestrator\node_modules\ws\lib\websocket.js:1192:20)
    at Receiver.emit (node:events:537:28)
    at Receiver.dataMessage (C:\snapshot\webrtc-telestrator\node_modules\ws\lib\receiver.js:560:14)
    at Receiver.getData (C:\snapshot\webrtc-telestrator\node_modules\ws\lib\receiver.js:478:17)
    at Receiver.startLoop (C:\snapshot\webrtc-telestrator\node_modules\ws\lib\receiver.js:167:22)
    at Receiver._write (C:\snapshot\webrtc-telestrator\node_modules\ws\lib\receiver.js:93:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
```
It looks like it tries to hook into a webcam, and not a screenshare.

This happens if you use `--httpHost 0.0.0.0` or no flag at all.

**Comment by BlankSourceCode** [comment]
@uujfwmnp Oops my bad, I accidently deleted an extra line. Try this:

[webrtc-telestrator-win.zip](https://github.com/BlankSourceCode/WebRTC-Telestrator/files/14202863/webrtc-telestrator-win.zip)

**Comment by uujfwmnp** [comment]
Screen sharing from the browser works again, but now I can't get the client to see the shared screen. The initial splash comes up, I press Join, and I only get the greenish background color of the page.

Progress though!

**Comment by BlankSourceCode** [comment]
@uujfwmnp Try also passing in the same ip address with `-wh` flag. So `webrtc-telestrator -hh 0.0.0.0 -wh 0.0.0.0`.

It's a bit odd to need to pass in the same thing on both, so if that works I'll probably just get rid of one and have them use the same ip.

**Comment by uujfwmnp** [comment]
That works, but defining the actual IP for hh and wh makes the host not pick up screens to be shared.

**Comment by BlankSourceCode** [comment]
@uujfwmnp Can you open the hosting browser to http://localhost:port even though you specified the ip via the flags?

**Comment by uujfwmnp** [comment]
No I can’t. If the IP is defined I have to use IP:8888 on all parts.

**Comment by BlankSourceCode** [comment]
@uujfwmnp is just binding to `0.0.0.0` (aka all network devices) out of the question for you? 

The issue is that the browser blocks sharing requests when using http:// (unless you specifically use localhost). It wants https:// which requires a valid certificate.

I'm not sure if there is another way to allow the browser to screen share over http, maybe there is some magic setting you can use.

**Comment by uujfwmnp** [comment]
I think the 0.0.0.0 will have to do. I’ll play with it a bit more and send an update later. Thank you for this!

**Comment by BlankSourceCode** [comment]
@uujfwmnp If you are using a chromium based browser to host the session (chrome/edge/etc.) there is a setting you can use.

If you go to `chrome://flags` or `edge://flags` and then find `unsafely-treat-insecure-origin-as-secure`, you can enable that flag, and add `http://<ip>:<port>` to the textbox. Then click the 'restart browser' button.

That should allow you to bind to just the single ip, and then use that same ip for the local host browser. It won't block the sharing request anymore because its treating that particular http:// address as https://

**Comment by uujfwmnp** [comment]
Oh that is a pretty slick workaround, this will work nicely for the funky edge case, thank you! Y'all got a place I can send over a thank you dono? :D

**Comment by uujfwmnp** [comment]
OK, one last gotcha I think. If I'm not defining -hh and -wh, just running 'webrtc-telestrator.exe' by itself, it's not connecting to the client site. I can run localhost for Host/OBS, and the hosting part works fine to share a screen, but the client would need the IP, and that won't load.

**Comment by BlankSourceCode** [comment]
@uujfwmnp I guess I changed the default with that branch from `undefined` to `localhost`, which isn't what we want.

It looks like undefined causes it to bind on 0.0.0.0 anyway, so I'm not sure what I really accomplished here, lol.

Well, I'll clean it up so that you can specify the bind address (with just one option) but add a note in the readme saying you'll need to use the browser flag setting to enable sharing.

**Comment by uujfwmnp** [comment]
🤣 Well it was an adventure! Thanks for your assistance again. I'll close this out~

**Comment by BlankSourceCode** [comment]
I know you closed it, but I added a PR for the changes anyway. It seems useful to be able to specify the bind address, even if you have to use a magic browser flag to actually get it to work.

I'm not sure if you actually got your scenario to work or not, but I'm glad you found the app useful!

**Comment by uujfwmnp** [comment]
While I wasn't able to test it on the streaming hardware to be used
for the edge case, I feel I was able to at least simulate it locally.

Used my cellphone's hotspot connected to my PC, which showed up as
Ethernet Connection 2, and it was assigned a 172.20.x IP. This was
different from my normal wired connection, on a 192.168 IP. I couldn't
get the client to connect to the hotspot IP, but I'm pretty sure this
is because the hotspot doesn't allow for hosted servers. However when
I switched the binding from the 172 to the 192 IP, everything worked.

I expect when I get access to the gear a bit later this month, that
it'll work just as simulated. 🤞
